name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2G

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-version: current
    - name: Build with Gradle
      run: gradle build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: build-artifacts
        path: build/libs
    - uses: softprops/action-gh-release@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "latest-26.1"
        prerelease: false
        name: "26.1 Build"
        files: |
          ./build/libs/*.jar
